name: Toby Harriman
favicon: null
layout_spectrum: 1
typography_spectrum: 0.44575876742601395
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050511'
    - '#193c5c'
    - '#2f5a84'
    - '#b69668'
    - '#96a3bd'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
